name: Build and Publish Rust Binary
on: [push]
jobs:
  build:
    runs-on: docker
    steps:
    - name: Set up Rust
      uses: msrd0/rust-toolchain@nightly
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build binary
      run: cargo build --release
    - name: Test location
      run: ls /workspace/musselman/version_name_generator/target/release
    - name: Publish binary
      uses: earl-warren/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: version_name_generator
