name: Build and Publish Rust Binary
on: [push]
jobs:
  build:
    runs-on: docker
        container:
          image: rust:1-alpine
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build binary
      run: cargo build --release
    - name: Publish binary
      uses: actions/upload-artifact@v3
      with:
        name: version_name_generator
        path: /workspace/musselman/version_name_generator/target/release/version_name_generator
